# Generated by Django 5.2.8 on 2025-12-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
