# Generated by Django 5.2.8 on 2025-12-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_product_show_on_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
